language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: OhGWq72o/rroVxsCGc7tImqqBvI2f1X0mQprbdt5pFIahshF4q8eNDHW9NvnnN2J90huPN164ID9rU9jwefi2Uqg0GsQ6/HMO4dDpiQsgKLW6JBLKG9C5yD27VZhF0fXfKmmwMn0RXOyQDDqfZU8Ht5NDwMRJlJGUqnKKHTAs2lZswFSj7LcfsUwp+fCoORwFJ/uE2HLg6oEWirUASccZyIHpSQm0YeN+DraG/DBiQmESn+VigkwNk51aVXa7KdEIdtesFwD0VJiPoBxATdwchJaKs9sboFIf7XGPcdaQW9dQ0gugjzSjwQKZwgmhPkd1vv09IZMRwGRp85G4QOSc83dhPK+vvZg5ANeK15cfgkAmWmDyNAtPKrEP2TjejGr5ooEOZqVai3fMz1iTw+Hr8wa8H17XuiADNmaMmtLK/TXN7Uiud605QW23dsRHFouTNlBQAiLP35IF4rmv66Nika8oULjOdHJhsAnMTilBLY9ockX/sXtGHPOIifEVl7l9RBq44Dbuby0RwiyphcaF2JTOxle7nr8DGQLLuAu2ehg4LpuEhRveiY8t9BYWNa5gk+paeajOFedMDNoFxLLElsboQUBFoK7WYcbp+Esr0lEX+wHUH7uDwlDepH8qJaIbK1r7bCArU4qT+j4Jf9XviWpwD/JFojOGw+e/JlOoGk=
  - secure: IzOlTVow81W2PMdn84lTB59BF5MrDVEncyYU4HLfgarKynRfYeQscH1YbM9t0jpK6QxXETysYrdNIszW5i8qGGZ++CTmuDfD0ZgfK27WCQ+6/GBqmlf8WpcRtIw8DfTZlC39Jjnjbrqxt3b6P8DrKudM/EyFuQjCioctG5sjfj7mX3CDzUQ5sYkKlgpdYNrnmVr5ab783syrfS0Gq5MijbBm5vMvTz6P3WEq+MjAt8ROpeh9g0y0+BP9+E4mh44meYwX5RukTlrAcJIazsFAlKjPBlrfFn85RwhSD2YjwmuJ+4ikt4XGuCHsSR7e/qfOL9esIr6eql5Sx44pNfG8bew8UP3qKU3qbfqj3/chsUG8IaNBDdKGzXe4gS8ly/8KGkH2UBdotRrbK0VR/ShUvlOcvYdz9FoL6O09LXMqBNE0WyOP0e3d0Q0PcWm83iJm7j9NwFfEfNCesAzs3aXYU/k8eOWFMlducsqpZ/3GsiWf0nTGcn4vdKsi011ZHjwSVWsuGw6c7AuAqdd44ImJqaU6yIbvohT85zLbSXCU5Mt8lZFxPIlieqiudBzvR+L147+HolqTGwHamT1ocKVMEs0sMVRba7xAZoia2t8IGzzUF4y2YeVdYcwRF0/7KLCC6Spw2e6wwzIkZSQM0ZjCE7u7txxx2/bb+n01T7U40v0=
  - secure: AJimBvjntRpG/4f09u2CBIWkQg0ZaVfFJA4zSZ7CJnWqCaAfIA6Mqeu2yWaZAlVi/K6oBjEG/QH2uVrkR8GzowMLCZhJ5x6xrJILy7QYYgMfjyNx122uF4ibRIxVrUuNXacbGENdkTfWD5iOOtNNpLjHvPrO+Mpek5XZWysWeJDhDuR6wwmfjomrvxEVQSt6Asdu+M8a7rTu38tkUvYoPsn2xSP6GnAb7+YZGjP1Ljyx4gd2/PPIef42qAjsBNbuJR/Lxah9y+/tZaw41ZEf7/ZumCKRlgD/R0GC42hN+XKIhoUW26gls5UwAREqve+23RbOMquzkefvjsWUH7NPFFL4YuuTk4Q4rqmVij0D/h7qc89PFoIQVkylro7OGGF5j2TQLLfKDkQTKULrrHCl3C0L9QddyUoZTv4A8uDDmHysUtQxPsc+1Ie5c2lGiBF/eLHjc/IBIwH4Y56xgyzEH+slP05NxeA8+sH1sXAQf4pWYEoXhxdupRkixSZv7Di6jDCreeskR4w9T/25ZX9GZyH86jkqWW4uaT1g3Ek7AYc/mySt4bSGAPLIK/3Rj9Xk+SExWGTErVu01APN/7cG6jorBM0MogHODlMdupF5+LwsgagN6tkEertw9M8Y/GghPop36wBM/OTzTAGUG5gBDB33XY+8OnY3gU0w1f6GBbE=
  - secure: T8KuO/vj6ROiyhQebfCz7y92xkhx6Sy0gwH7mnK8ggE+tiWw7zU++XpuYXse7qzqUXuTd2PsjXXeuM9YUV/NMnpIiv5B92et3aFgasJwmZ7RJBrSxH2vlWT8VIW0anuQ1ExhHpMea2UfKUaQXd2q6JKiuMUfvVoAUcT2X3AaKN0UdnhBtee3KYhGPwNo9ZVjq636mf+b4rFfRag4omZUJCQ42IXF77wuDbb7R9S+rePEM7YKDXz2KZ348X39Mrd5DscHswQb/I0NvAc95a6MCvWIb0JF81ZOAGiuRRgjQ411ebLzVjdAt+Hn3GcRBBihL/lW4/WqtJGOFa/hFt0/QAWyoDLC7pnIUQ4kCdK5V74XKao1yB/jWJWrtmtXXtBYUcUcjEv1qwb6R09PdTuCsEUEWd2ZFkLLQfrdJPtqgRxzIldwrcVWu+nx4Wr1ZD1p6hQM3geUehfW2G1NYMUoFkvRlLbu5KIr9NmuKP8gwwSeSpRO3jz0+AxgDPHsT7CbkRjlSEEAJOQ+1ZFdO0Kjg6Hjb9DnJAECPimT41han2xDBcwVGF2ES6nsgj44qWWlYmtld4p/AuZZp3HoHZLPcap0r5zY8Ivlni4G/1kPYG4Az49o2gRIqtRsm1EwVIvzFFFrELi//XnOJ/TV5bzL+I6GWVJC+aEm5VOZJIHULM0=
addons:
  ssh_known_hosts:
  - github.com
install:
- mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
before_script:
- sed -i "s/BINTRAY_USER/${BINTRAY_USER}/g" .travis/mvn-settings.xml
- sed -i "s/BINTRAY_API_KEY/${BINTRAY_API_KEY}/g" .travis/mvn-settings.xml
script:
- mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
- provider: script
  skip_cleanup: true
  script:
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION}
    -Dsonar.login=${SONAR_TOKEN}
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST = false"
