language: java
sudo: false
branches:
  only:
  - master
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: KTgmwktCR+viJ8xuVD0vDiQ84d/CautKcjUsnzgNpu209StqfU5q1GdbsoExsZUed5YvmAsiNBs50Ftm8Zt2UUJwYT33zvJrqTjy9Z5YfcXICmDSSM3HMucfwDwz9u0DwFgbhnMzlgDicRox22cJRG1exjGmUskBJ9Sp/tDW7Wi51NFKKRkwTmxD1XUz8jKBXnAfKQR8ZWBXD6r08yB4gyQU8xvl9h6y7JYjd7v01Gn1Et+vGUwEJML9y6seYGsi+xRuVvr+e9BlAu9i2k0q3h3dqlmSujPFHM8s4soZTY2aKo92r2ZOUMqu6cn/orYeoEJ5Ps0J1ac8i0g1K9obDk5Oplkf9wS286MaRnZwVXWyLYCaudVIs86tkvX6hshkUPv7eaXYFpN48eUsANKrL1VF600rrZyAaDkgYOCy5zXvRle4tp6TTEihXLRFW7uUc+cdMfUFqftT2HoJxJG5L5IfMdseExhHYnK0zYrlrWRh98A6C6PHDx/IoPDeOMq5AZXeQhEA6eW1+wqlCKtCrizdwHZJ7jNtZPOekWWFk9USe4yBR2awlnRral32DmOCPcomBJq3Nfm65ARDOaLTYayh9UmkXduWMRy0c1BwGFTw4TUDCfpztsay9sWzdZoNq73S1ZoxSiG3H5JblvRFbPComIuxmig9mVK1Ahlbk6o=
  - secure: rEqKP9K2zaCVm8sE1RHYoXiRUv/fl38jM9oFI3fgI03rSVePyTe1GOvlxK2yvjnbH6r0g5wOxfsxP46PGSjE7U/QccJk5cjHjqN2bxqYORa3cBKtFrQYBN61fidBVXVAqOe4vEodng5BQySJrxB7dihjSkMozsnYQIakS0vwwh41YWYVsDdcpKGEYlNvn7HqPCUu9yKaH3Ds5wKa9cou0LGG5nvFqPCraLFw9+UJvWkxJW42Kfzg+F/ldDDIe/SsycwJaDEWJTBxauSDI0Ttbab6FZ50aiPyLXXyWh44iRPuv67Y/Nwq2+cBU5GTymrcXBRyKXWr3GFvh1pqOSIiI4cDPB0rpotD61cMGgL9w4bJ3vMfrF/LPvdEUwfwUx7OCdeUzHcBgDbixS8Mue0/djm4RwyBp7aUwxTuxYRhd4hs3RHuCNqxnGgfCh2T8BfBMfws482qUtsaZn/Lwo+4JIRKB7Rt5dtYEHU5k/CReONU+PoF1rQrkaLVJYIIC5XTObxcyUyw0V9RSqFJsGBh8HODLgxHI2G4HO3bmSUAtNK83quLZNn5aUTx3GSFB7ftHPRyTN20Zf/2HkWp0FU6zDU/PLXpsSED/EByWIiqQ6VNIkams9XrcqnbZDWlBobibh8ljpic6wFDIlwF/AnAUsnLPJ3T/iKFtIuyFf46bgE=
  - secure: JcXY+gowEm6Mf5Gks8/oAmfBV8P6GQycdDZOa1Uyv0lQnx5Ku8gcgOLQv7s4yaPXydjvzSFteuT+l7wpzACYJO5Cp/JSS8QFNmzJ4f9GOhRellNht9NUac1zG6yiTsNBzJAVxbfAuii7n4U8H0LT1bDVaOu1R4k8eBALdCZyPKfLv8A8po7BzdB3Yg1DFZJCDbpH3R9tWm8C51vIMTci8Ns3FFQghb4Oj2wjTst6dtxnG1ZG0F/Wg8OLUDUDxCklhuVtdv2fHQ2rZgqyBfTfSq7dt+0pVTTWMbJxCzG+8teSKoVsFBXZSjXBqs1QuDIRiTlybJGuewUYjKIGW84acgFaJ2VEfMaW533a7UMCigTn2ItnOXbW+ZbXHmn2p6A+VFZFbj8xYRDOeSfV+zGYoMxN1th+Rkyrgs3D0qeUqDd31JboZKiP6SApbDFAsHWs2afhkrN/ZrcthHgJ6D9eq6ZpQ1fJsW2N44U8uyFSGCSaGSw3/MBvIONKp6I/dsEca9XqSvXBwp7NxkyhSJDFnV0jnqICUhOEuRtzTSe1rn9q7gpEn5iG2A9UJR/z5l3zH5Z1Cf4dnWO6IeNF8BF47wDiAaeMtTv83AblAMz18mmW2Nidg/JPwBg1F73LPIYKlDvbcI/riOom9/DGpCboCYy2fPwYJrluel0ERCdfdP8=
  - secure: oxn1ud15SW2soS1zXhMGbr277TBo+J4QCJ3ahTas1+NNcWeI/2lS2nUNO6Kxq/ZfVAS4zeBm5sRBCLbsAmMTxZIyBhJBpqMWLjqfRw6I3Po0hEpcg9hlQPPj4WFb5DoHX1WaNeWINW6++8WDyjIIcM2I06+HMSo0FjXdkWxSbt0u2XVwPOm/yH0nfoYDF4fiFdXlGNJEVD6dQ15xuj3zfEoQlhjkG0mQ6wefEu/RAQTnfBhGJP/NBQGJaW119xQz0oFJjd5hGdOlg5hcT77GmNuKe4ICba4+Wjx01vpmzmjivgSrDOZHftwX22G842JtutbBbXcgbuOFJTG2TdrZYG9ewEL2EFdvxUv7P3Cp8YiMHz1AmiwdPjWXCfHsK8AF5Nbpg+3YJx7wbUEMyPYT3a65p7UnN0bNQzvzfcEXeCbXwtoROIkScb4u9BjKrI5krB3NPqCIGQUE7ziZzsE9rl4PkY3nAzw/xC08SoIx/FWqlU/ntQp7sUvGRdAAGsgiv5Qx3JkNy5FDYHJsKoyuPez5MiNdj1prLPSP+Awe1ydXszM/yPFyTXW6fwuIyOfL2pTPoxwxfU7RUzf/57jnHGfwlqYOEfYtLqvoodBZHLjbnTcKL4npHZ1XMFh+8qilcnRRL575oWoUnm31TmLn8NClO7SMYnPx/yv+YfZP+DM=
  - secure: rHKbCLGrcCPIlrfSTnzalO0yRQ20hy27M9X+/IXFbCILjEiFvmrzFkjHLxcbXeNFEKEUc9q0k4Wq/qXaQE/HW51aHfisC9W6j7wbbkU+bGatqot1K4uEXjgvoltKZt7x2lhznEkN+Iu4NvtXXhLhsd/G3uvZC1T6GnnIwGsnolKXPnPlKgiDovGsnlrxCWua5LhcA97P2QQJiR+3oS3DH+AuAJffRrdfUATPicC5YUouJUL/ATVk9OzPBH7yyqZ6gosT6u9R6cNWZ9Bm0wSpRY+pRHDi53D31rDX5SP4aYfJj5668ScaioQzEKCK5VBM11EAv4Qav01rwPkM4Oyo/dLeJHIrl3JDPcfWnyjX4zEdGDjJhQGlBQOAgsM4syzA4XOC621CdjFa29uEucGn4prAzK+3dMWGM/32+oLXMZHao7uRutvYdBc2T/TLouE4Jse7ErJ8n1zoS1VUEnvxNgME44xjind+d2nkBltFm/skLr+8aWLNvtI71lVuQFYK14t50uK3n4+IjoaXd95sYyEawhRThkRtM/7IRcu68VxRM9tpZpDSwl/6Uyllku7mF5Z68AnEdI1yCZWSF9gk4Oyc/wffxMTA1Tzw0S3YNZXMi7gMYUd7dkP3rLkKBQqNSsBgMSxEjN2sUPZFfg7mBzgO1Qyv11QU9ZBBxRY3M/I=
addons:
  ssh_known_hosts:
  - github.com
install:
  - mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
before_script:
  - sed -i "s/BINTRAY_USER/${BINTRAY_USER}/g" .travis/mvn-settings.xml
  - sed -i "s/BINTRAY_API_KEY/${BINTRAY_API_KEY}/g" .travis/mvn-settings.xml
script:
  - mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.login=${SONAR_TOKEN}
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: pages
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN}
    local_dir: target/site/
    on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST = false
