language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
git:
  depth: false
env:
  global:
      # GITHUB_TOKEN
    - secure: NEfcvOqEe4xsS8obixGWemljU1KTjz+ZilvcrFCQiffbJTBHopIHsQ5/zlkscx2gz8sjmM3T6SWNMD+h7MKoITpGS3/EoK4yuGUj4fLZdZppFWHcqLTtC23ZGdtrSV9sCgXuWLL1Likx8T/6jN94iLcw+qvW3z++kPmZIBdi97xhRxXg6Un45y8eY+TDDceXYpVhIdn4i8XOyyo27Tt+a4oF/uOAEUPqju7ByTlpZJ7VYHeIsZzgZczSez+aPxKhyuOfJVscbqYCmVtuBbV91mvfGXSWrD5XnsLM74cS0eX9b4WZ6ZfMRTK9D4Nwp0UorVfzaMJvLTevmd5gzOHrSVUygCJ/B+NLnoHpoI6nntCO3kiaOEsAgmGnjtYZNV4asXMYAlRZsTmzrCNYCLh3sZa7oBet9BEb6UQDJu7rOVNwKoXvQ3elgYntIr/zhaBubBE9I+Aoh+aIkVS2B+BCZ9oX8/jq7pEHweDiU9hLTc+k7jk5yT7tc+X68zQQ4nbW8nashnmQ8M3tj0aiBNd3wA/foIurq+hEHGKrHDG6RMQhNDKfBKqVtXD6nXifVRmHq6/+XIzjOxRG7Y0XnclX9bn8pWE2zGNNERXFIa/kz2Y8L4QZis/aZ8E3JMrejsTirq/C392kctTJ4YrdPyl5CDyGVlDafARQGj73VCZT3Dc=
      # SONAR_TOKEN
    - secure: ItbKR20XJh5eXpVFBwDgKAabTy3I2Gm+djyRLM2eFWvdswseawoJavjsJqBqSpBoQ3PqQZp4EqqCivTMJXx4iD8eue4qWbzJOAfWVtaKUiT0/NovrSkqWVES7GMjR81sACmfCr8h70nWe6l1JtanFhuQYbML5JXxswo3N2WGiIg68KLbltsflaUtfIEhyVBBVRtQVegYcQV4WfjQTXUUu61yrOpOdaFffEpkn5ijKCO4i1ushQT3CL+I/kuVZB0Uu+a9FUqNjJl2sMeaBYeN125jQxqR8wjKO2V0KP3cUBKICBIRV82kPHfZZTwWTM86J6OyQt1HN7IqX6vMv2X/dc3RW2O8hLaU617WjgOyR19JvmWHIfB+xXnL6VUlxKYoTAiFX98rPSxhp5fFsspi+rqyaOSHkwwiJnCB1VWFeo9gqNbHAwBox8re7jF6WpLBF/0HNw52SVPQ1fnMkmnyYurq87w/C3WgC2zP8H7diI4iv4qRcDfWL8+fAG3mymhSwt79tIku5VBxF6n8U5hsB3u71TtGb5lMHULrRPv3PqW0pbsxcTSS+h6I3ooUVebSouc8vrJlh5s7z066FG7WURvzbAueO+RSsTsdcn6KF3yvZtsgCnvLZeTyd8UVlT2AYpAMfjtAeaGbtJ4Ooc3LBMQXwdaVF7o7P1eJzIP5ozI=
script:
  - bash .travis/maven-install.sh
  - bash .travis/re-generate-example-project.sh
