#!/usr/bin/env bash


ARCHETYPE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
ARTIFACT_NAME="co-farkas-example-simple"
GIT_REMOTE="https://co-farkas:${GITHUB_TOKEN}@github.com/co-farkas/${ARTIFACT_NAME}.git"
GIT_DIR="/tmp/$(uuidgen)"
MVN_DIR="/tmp/${ARTIFACT_NAME}"

echo MVN_DIR ${MVN_DIR}
echo GIT_DIR ${GIT_DIR}

cd /tmp
mvn archetype:generate \
  -DinteractiveMode=false \
  -DarchetypeGroupId=co-farkas.maven.archetypes \
  -DarchetypeArtifactId=co-farkas-maven-archetype-simple \
  -DarchetypeVersion=${ARCHETYPE_VERSION} \
  -DgroupId=co-farkas.examples \
  -DartifactId=co-farkas-example-simple \
  -Dversion=${ARCHETYPE_VERSION} \
  -Dpackage=co.farkas.example.simple \
  -DcopyrightYear=2019 \
  -DcopyrightOwner="Mihaly Farkas" \
  -DgithubAccount=co-farkas \
  -DprojectName="Farkas Co - Example - Simple Project" \
  -DprojectDescription="Simple Maven project."

git clone ${GIT_REMOTE} ${GIT_DIR} --depth=1

cd ${GIT_DIR}
rm -rf ./*
mv .git _git
rm -rf .[!.] .??*
mv _git .git
echo "*****************************************"
ls -al
echo "*****************************************"

mv ${MVN_DIR}/* ${GIT_DIR}/
mv ${MVN_DIR}/.* ${GIT_DIR}/
echo "*****************************************"
ls -al
echo "*****************************************"

travis encrypt BINTRAY_USER="${BINTRAY_USER}" --add
travis encrypt BINTRAY_API_KEY="${BINTRAY_API_KEY}" --add
travis encrypt SONAR_ORGANIZATION="co-farkas-github" --add
travis encrypt SONAR_TOKEN="${SONAR_TOKEN}" --add
travis encrypt GITHUB_TOKEN="${GITHUB_TOKEN}" --add

git add . -A
git commit -m "Re-generated by co-farkas.maven.archetypes:co-farkas-maven-archetype-simple:${ARCHETYPE_VERSION}"
git push
