language: java
sudo: false
branches:
  only:
    - master
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
env:
  global:
addons:
  ssh_known_hosts:
    - github.com
install:
  - mvn dependency:go-offline test clean --update-snapshots --fail-never -DskipTests=true
before_script:
  - sed -i "s/BINTRAY_USER/${BINTRAY_USER}/g" .travis/mvn-settings.xml
  - sed -i "s/BINTRAY_API_KEY/${BINTRAY_API_KEY}/g" .travis/mvn-settings.xml
script:
  - mvn deploy site --settings=.travis/mvn-settings.xml -Ddependency.locations.enabled=false
